# Generated by Django 3.2.16 on 2023-01-05 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField(unique=True)),
                ('table_size', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
            options={
                'ordering': ['table_id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.IntegerField(choices=[(1, '10:00'), (2, '10:30'), (3, '11:00'), (4, '11:30'), (5, '12:00'), (6, '12:30'), (7, '13:00'), (8, '13:30'), (9, '14:00'), (10, '17:00'), (11, '17:30'), (12, '18:00'), (13, '18:30'), (14, '19:00'), (15, '19:30')], default=1)),
                ('number_guests', models.IntegerField()),
                ('special_requests', models.TextField()),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='bookings.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reservation_date', 'reservation_time', 'booked_table'],
            },
        ),
    ]
