# Generated by Django 3.2.16 on 2023-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2),
        ),
    ]
