# Generated by Django 3.2.16 on 2023-01-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(max_length=10),
        ),
    ]
