# Generated by Django 3.2.16 on 2023-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
