# Generated by Django 3.2.16 on 2023-01-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reservation_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_guests',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
