# Generated by Django 3.2.16 on 2023-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_reservation_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.IntegerField(choices=[(1, '10:00'), (2, '10:30'), (3, '11:00'), (4, '11:30'), (5, '12:00'), (6, '12:30'), (7, '13:00'), (8, '13:30'), (9, '14:00'), (10, '17:00'), (11, '17:30'), (12, '18:00'), (13, '18:30'), (14, '19:00'), (15, '19:30')], default=1),
        ),
    ]
